// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// PermissionInfo is the golang structure of table permission_info for DAO operations like Where/Data.
type PermissionInfo struct {
	g.Meta     `orm:"table:permission_info, do:true"`
	Id         interface{} //
	ParentId   interface{} // 父级ID
	Path       interface{} // 菜单路径
	Component  interface{} // 菜单对应的组件名称-前端文件路径
	Redirect   interface{} // 重定向路径
	Name       interface{} // 菜单名称
	Title      interface{} // 菜单元数据标题
	MetaIcon   interface{} // 菜单元数据icon图标
	AlwaysShow interface{} // 是否总是显示菜单项
	NoCache    interface{} // 是否缓存菜单项
	CreatedAt  *gtime.Time //
	UpdatedAt  *gtime.Time //
	DeletedAt  *gtime.Time //
}
