// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// PermissionInfo is the golang structure of table permission_info for DAO operations like Where/Data.
type PermissionInfo struct {
	g.Meta    `orm:"table:permission_info, do:true"`
	Id        interface{} //
	Name      interface{} // 权限名称
	Path      interface{} // 路径
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
	DeletedAt *gtime.Time //
	Component interface{} // 前端文件地址
	ParentId  interface{} // 父级ID
	Redirect  interface{} // 跳转地址
	Keepalive interface{} // 1 缓存 2 不存在
	Hidden    interface{} //
	Sort      interface{} // 排序字段
	Icon      interface{} // 菜单图标
}
