// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// PermissionInfo is the golang structure for table permission_info.
type PermissionInfo struct {
	Id         int         `json:"id"         description:""`
	ParentId   int         `json:"parentId"   description:"父级ID"`
	Path       string      `json:"path"       description:"菜单路径"`
	Component  string      `json:"component"  description:"菜单对应的组件名称-前端文件路径"`
	Redirect   string      `json:"redirect"   description:"重定向路径"`
	Name       string      `json:"name"       description:"菜单名称"`
	Title      string      `json:"title"      description:"菜单元数据标题"`
	MetaIcon   string      `json:"metaIcon"   description:"菜单元数据icon图标"`
	AlwaysShow int         `json:"alwaysShow" description:"是否总是显示菜单项"`
	NoCache    int         `json:"noCache"    description:"是否缓存菜单项"`
	CreatedAt  *gtime.Time `json:"createdAt"  description:""`
	UpdatedAt  *gtime.Time `json:"updatedAt"  description:""`
	DeletedAt  *gtime.Time `json:"deletedAt"  description:""`
}
